## HYPOTHESIS TESTING ASSIGNMENT

### QUESTION 1 

In [74]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [75]:
# Load the dataset
data=pd.read_csv("Cutlets.csv")
data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [76]:
unitA=pd.Series(data.iloc[:,0])
unitA

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [77]:
unitB=pd.Series(data.iloc[:,0])
unitB

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [78]:
# 2-sample 2-tail ttest:   stats.ttest_ind(array1,array2)     # ind -> independent samples
p_value=stats.ttest_ind(unitA,unitB)
p_value

Ttest_indResult(statistic=0.0, pvalue=1.0)

In [84]:
pvalue=1.0    # 2-tail probability 

In [80]:
# compare p_value with 
α = 0.05 #(At 5% significance level)

In [86]:
# Accept Null Hypothesis
if pvalue<α:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

accept null hypothesis


### QUESTION 2

In [63]:
# load the dataset
data=pd.read_csv('LabTAT.csv')
data.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [65]:
data.value_counts()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
138.30        176.63        193.08        128.93          1
143.52        168.20        213.18        124.06          1
186.22        182.17        189.98        167.83          1
185.87        194.24        201.17        149.96          1
185.42        205.27        177.62        172.72          1
                                                         ..
171.65        142.38        187.60        167.07          1
171.64        188.49        202.95        167.62          1
171.41        185.67        180.35        145.40          1
170.61        169.11        203.24        165.95          1
216.39        193.28        177.76        161.42          1
Length: 120, dtype: int64

In [67]:
# Anova ftest statistics: stats.f_oneway(column-1,column-2,column-3,column-4)
stats.f_oneway(data.iloc[:,0],data.iloc[:,1],data.iloc[:,2],data.iloc[:,3] )


F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [89]:
p__value= 2.1156708949992414e-57  
α = 0.05

In [90]:
# Reject Null Hypothesis
if p__value<α:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

reject null hypothesis


### QUESTION 3 

In [24]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency

In [25]:
# load the dataset
data= pd.read_csv('BuyerRatio.csv')
data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [26]:
# Make dimensional array
obs=np.array([[50,142,131,70],[435,1523,1356,750]])
obs

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [27]:
# Chi2 contengency independence test
chi2_contingency(obs) # o/p is (Chi2 stats value, p_value, df, expected obsvations)

Chi2ContingencyResult(statistic=1.595945538661058, pvalue=0.6603094907091882, dof=3, expected_freq=array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [91]:
# Compare p_value with 
α = 0.05
p___value=0.6603094907091882

In [92]:
# Accept Null Hypothesis
if p___value<α:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

accept null hypothesis


### QUESTION 4

In [30]:
# load the dataset
data=pd.read_csv('Costomer+OrderForm.csv')
data

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [37]:
data.describe()

Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [23]:
data.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [24]:
data.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [25]:
data.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [26]:
data.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [27]:
# Make a contingency table
obs=np.array([[271,267,269,280],[29,33,31,20]])
obs

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [28]:
# Chi2 contengency independence test
chi2_contingency(obs) # o/p is (Chi2 stats value, p_value, df, expected obsvations)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [93]:
# Compare p_value with 
α = 0.05
p____value=0.2771020991233135
if p____value<α:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

accept null hypothesis
